hico_verb_object_list = [('board', 'airplane'),
 ('direct', 'airplane'),
 ('exit', 'airplane'),
 ('fly', 'airplane'),
 ('inspect', 'airplane'),
 ('load', 'airplane'),
 ('ride', 'airplane'),
 ('sit on', 'airplane'),
 ('wash', 'airplane'),
 ('no interaction', 'airplane'),
 ('carry', 'bicycle'),
 ('hold', 'bicycle'),
 ('inspect', 'bicycle'),
 ('jump', 'bicycle'),
 ('hop on', 'bicycle'),
 ('park', 'bicycle'),
 ('push', 'bicycle'),
 ('repair', 'bicycle'),
 ('ride', 'bicycle'),
 ('sit on', 'bicycle'),
 ('straddle', 'bicycle'),
 ('walk', 'bicycle'),
 ('wash', 'bicycle'),
 ('no interaction', 'bicycle'),
 ('chase', 'bird'),
 ('feed', 'bird'),
 ('hold', 'bird'),
 ('pet', 'bird'),
 ('release', 'bird'),
 ('watch', 'bird'),
 ('no interaction', 'bird'),
 ('board', 'boat'),
 ('drive', 'boat'),
 ('exit', 'boat'),
 ('inspect', 'boat'),
 ('jump', 'boat'),
 ('launch', 'boat'),
 ('repair', 'boat'),
 ('ride', 'boat'),
 ('row', 'boat'),
 ('sail', 'boat'),
 ('sit on', 'boat'),
 ('stand on', 'boat'),
 ('tie', 'boat'),
 ('wash', 'boat'),
 ('no interaction', 'boat'),
 ('carry', 'bottle'),
 ('drink with', 'bottle'),
 ('hold', 'bottle'),
 ('inspect', 'bottle'),
 ('lick', 'bottle'),
 ('open', 'bottle'),
 ('pour', 'bottle'),
 ('no interaction', 'bottle'),
 ('board', 'bus'),
 ('direct', 'bus'),
 ('drive', 'bus'),
 ('exit', 'bus'),
 ('inspect', 'bus'),
 ('load', 'bus'),
 ('ride', 'bus'),
 ('sit on', 'bus'),
 ('wash', 'bus'),
 ('wave', 'bus'),
 ('no interaction', 'bus'),
 ('board', 'car'),
 ('direct', 'car'),
 ('drive', 'car'),
 ('hose', 'car'),
 ('inspect', 'car'),
 ('jump', 'car'),
 ('load', 'car'),
 ('park', 'car'),
 ('ride', 'car'),
 ('wash', 'car'),
 ('no interaction', 'car'),
 ('dry', 'cat'),
 ('feed', 'cat'),
 ('hold', 'cat'),
 ('hug', 'cat'),
 ('kiss', 'cat'),
 ('pet', 'cat'),
 ('scratch', 'cat'),
 ('wash', 'cat'),
 ('chase', 'cat'),
 ('no interaction', 'cat'),
 ('carry', 'chair'),
 ('hold', 'chair'),
 ('lie on', 'chair'),
 ('sit on', 'chair'),
 ('stand on', 'chair'),
 ('no interaction', 'chair'),
 ('carry', 'couch'),
 ('lie on', 'couch'),
 ('sit on', 'couch'),
 ('no interaction', 'couch'),
 ('feed', 'cow'),
 ('herd', 'cow'),
 ('hold', 'cow'),
 ('hug', 'cow'),
 ('kiss', 'cow'),
 ('lasso', 'cow'),
 ('milk', 'cow'),
 ('pet', 'cow'),
 ('ride', 'cow'),
 ('walk', 'cow'),
 ('no interaction', 'cow'),
 ('clean', 'dining table'),
 ('eat at', 'dining table'),
 ('sit at', 'dining table'),
 ('no interaction', 'dining table'),
 ('carry', 'dog'),
 ('dry', 'dog'),
 ('feed', 'dog'),
 ('groom', 'dog'),
 ('hold', 'dog'),
 ('hose', 'dog'),
 ('hug', 'dog'),
 ('inspect', 'dog'),
 ('kiss', 'dog'),
 ('pet', 'dog'),
 ('run', 'dog'),
 ('scratch', 'dog'),
 ('straddle', 'dog'),
 ('train', 'dog'),
 ('walk', 'dog'),
 ('wash', 'dog'),
 ('chase', 'dog'),
 ('no interaction', 'dog'),
 ('feed', 'horse'),
 ('groom', 'horse'),
 ('hold', 'horse'),
 ('hug', 'horse'),
 ('jump', 'horse'),
 ('kiss', 'horse'),
 ('load', 'horse'),
 ('hop on', 'horse'),
 ('pet', 'horse'),
 ('race', 'horse'),
 ('ride', 'horse'),
 ('run', 'horse'),
 ('straddle', 'horse'),
 ('train', 'horse'),
 ('walk', 'horse'),
 ('wash', 'horse'),
 ('no interaction', 'horse'),
 ('hold', 'motorcycle'),
 ('inspect', 'motorcycle'),
 ('jump', 'motorcycle'),
 ('hop on', 'motorcycle'),
 ('park', 'motorcycle'),
 ('push', 'motorcycle'),
 ('race', 'motorcycle'),
 ('ride', 'motorcycle'),
 ('sit on', 'motorcycle'),
 ('straddle', 'motorcycle'),
 ('turn', 'motorcycle'),
 ('walk', 'motorcycle'),
 ('wash', 'motorcycle'),
 ('no interaction', 'motorcycle'),
 ('carry', 'person'),
 ('greet', 'person'),
 ('hold', 'person'),
 ('hug', 'person'),
 ('kiss', 'person'),
 ('stab', 'person'),
 ('tag', 'person'),
 ('teach', 'person'),
 ('lick', 'person'),
 ('no interaction', 'person'),
 ('carry', 'potted plant'),
 ('hold', 'potted plant'),
 ('hose', 'potted plant'),
 ('no interaction', 'potted plant'),
 ('carry', 'sheep'),
 ('feed', 'sheep'),
 ('herd', 'sheep'),
 ('hold', 'sheep'),
 ('hug', 'sheep'),
 ('kiss', 'sheep'),
 ('pet', 'sheep'),
 ('ride', 'sheep'),
 ('shear', 'sheep'),
 ('walk', 'sheep'),
 ('wash', 'sheep'),
 ('no interaction', 'sheep'),
 ('board', 'train'),
 ('drive', 'train'),
 ('exit', 'train'),
 ('load', 'train'),
 ('ride', 'train'),
 ('sit on', 'train'),
 ('wash', 'train'),
 ('no interaction', 'train'),
 ('control', 'tv'),
 ('repair', 'tv'),
 ('watch', 'tv'),
 ('no interaction', 'tv'),
 ('buy', 'apple'),
 ('cut', 'apple'),
 ('eat', 'apple'),
 ('hold', 'apple'),
 ('inspect', 'apple'),
 ('peel', 'apple'),
 ('pick', 'apple'),
 ('smell', 'apple'),
 ('wash', 'apple'),
 ('no interaction', 'apple'),
 ('carry', 'backpack'),
 ('hold', 'backpack'),
 ('inspect', 'backpack'),
 ('open', 'backpack'),
 ('wear', 'backpack'),
 ('no interaction', 'backpack'),
 ('buy', 'banana'),
 ('carry', 'banana'),
 ('cut', 'banana'),
 ('eat', 'banana'),
 ('hold', 'banana'),
 ('inspect', 'banana'),
 ('peel', 'banana'),
 ('pick', 'banana'),
 ('smell', 'banana'),
 ('no interaction', 'banana'),
 ('break', 'baseball bat'),
 ('carry', 'baseball bat'),
 ('hold', 'baseball bat'),
 ('sign', 'baseball bat'),
 ('swing', 'baseball bat'),
 ('throw', 'baseball bat'),
 ('wield', 'baseball bat'),
 ('no interaction', 'baseball bat'),
 ('hold', 'baseball glove'),
 ('wear', 'baseball glove'),
 ('no interaction', 'baseball glove'),
 ('feed', 'bear'),
 ('hunt', 'bear'),
 ('watch', 'bear'),
 ('no interaction', 'bear'),
 ('clean', 'bed'),
 ('lie on', 'bed'),
 ('sit on', 'bed'),
 ('no interaction', 'bed'),
 ('inspect', 'bench'),
 ('lie on', 'bench'),
 ('sit on', 'bench'),
 ('no interaction', 'bench'),
 ('carry', 'book'),
 ('hold', 'book'),
 ('open', 'book'),
 ('read', 'book'),
 ('no interaction', 'book'),
 ('hold', 'bowl'),
 ('stir', 'bowl'),
 ('wash', 'bowl'),
 ('lick', 'bowl'),
 ('no interaction', 'bowl'),
 ('cut', 'broccoli'),
 ('eat', 'broccoli'),
 ('hold', 'broccoli'),
 ('smell', 'broccoli'),
 ('stir', 'broccoli'),
 ('wash', 'broccoli'),
 ('no interaction', 'broccoli'),
 ('blow', 'cake'),
 ('carry', 'cake'),
 ('cut', 'cake'),
 ('eat', 'cake'),
 ('hold', 'cake'),
 ('light', 'cake'),
 ('make', 'cake'),
 ('pick up', 'cake'),
 ('no interaction', 'cake'),
 ('carry', 'carrot'),
 ('cook', 'carrot'),
 ('cut', 'carrot'),
 ('eat', 'carrot'),
 ('hold', 'carrot'),
 ('peel', 'carrot'),
 ('smell', 'carrot'),
 ('stir', 'carrot'),
 ('wash', 'carrot'),
 ('no interaction', 'carrot'),
 ('carry', 'cell phone'),
 ('hold', 'cell phone'),
 ('read', 'cell phone'),
 ('repair', 'cell phone'),
 ('talk on', 'cell phone'),
 ('text on', 'cell phone'),
 ('no interaction', 'cell phone'),
 ('check', 'clock'),
 ('hold', 'clock'),
 ('repair', 'clock'),
 ('set', 'clock'),
 ('no interaction', 'clock'),
 ('carry', 'cup'),
 ('drink with', 'cup'),
 ('hold', 'cup'),
 ('inspect', 'cup'),
 ('pour', 'cup'),
 ('sip', 'cup'),
 ('smell', 'cup'),
 ('fill', 'cup'),
 ('wash', 'cup'),
 ('no interaction', 'cup'),
 ('buy', 'donut'),
 ('carry', 'donut'),
 ('eat', 'donut'),
 ('hold', 'donut'),
 ('make', 'donut'),
 ('pick up', 'donut'),
 ('smell', 'donut'),
 ('no interaction', 'donut'),
 ('feed', 'elephant'),
 ('hold', 'elephant'),
 ('hose', 'elephant'),
 ('hug', 'elephant'),
 ('kiss', 'elephant'),
 ('hop on', 'elephant'),
 ('pet', 'elephant'),
 ('ride', 'elephant'),
 ('walk', 'elephant'),
 ('wash', 'elephant'),
 ('watch', 'elephant'),
 ('no interaction', 'elephant'),
 ('hug', 'fire hydrant'),
 ('inspect', 'fire hydrant'),
 ('open', 'fire hydrant'),
 ('paint', 'fire hydrant'),
 ('no interaction', 'fire hydrant'),
 ('hold', 'fork'),
 ('lift', 'fork'),
 ('stick', 'fork'),
 ('lick', 'fork'),
 ('wash', 'fork'),
 ('no interaction', 'fork'),
 ('block', 'frisbee'),
 ('catch', 'frisbee'),
 ('hold', 'frisbee'),
 ('spin', 'frisbee'),
 ('throw', 'frisbee'),
 ('no interaction', 'frisbee'),
 ('feed', 'giraffe'),
 ('kiss', 'giraffe'),
 ('pet', 'giraffe'),
 ('ride', 'giraffe'),
 ('watch', 'giraffe'),
 ('no interaction', 'giraffe'),
 ('hold', 'hair drier'),
 ('operate', 'hair drier'),
 ('repair', 'hair drier'),
 ('no interaction', 'hair drier'),
 ('carry', 'handbag'),
 ('hold', 'handbag'),
 ('inspect', 'handbag'),
 ('no interaction', 'handbag'),
 ('carry', 'hot dog'),
 ('cook', 'hot dog'),
 ('cut', 'hot dog'),
 ('eat', 'hot dog'),
 ('hold', 'hot dog'),
 ('make', 'hot dog'),
 ('no interaction', 'hot dog'),
 ('carry', 'keyboard'),
 ('clean', 'keyboard'),
 ('hold', 'keyboard'),
 ('type on', 'keyboard'),
 ('no interaction', 'keyboard'),
 ('assemble', 'kite'),
 ('carry', 'kite'),
 ('fly', 'kite'),
 ('hold', 'kite'),
 ('inspect', 'kite'),
 ('launch', 'kite'),
 ('pull', 'kite'),
 ('no interaction', 'kite'),
 ('cut with', 'knife'),
 ('hold', 'knife'),
 ('stick', 'knife'),
 ('wash', 'knife'),
 ('wield', 'knife'),
 ('lick', 'knife'),
 ('no interaction', 'knife'),
 ('hold', 'laptop'),
 ('open', 'laptop'),
 ('read', 'laptop'),
 ('repair', 'laptop'),
 ('type on', 'laptop'),
 ('no interaction', 'laptop'),
 ('clean', 'microwave'),
 ('open', 'microwave'),
 ('operate', 'microwave'),
 ('no interaction', 'microwave'),
 ('control', 'mouse'),
 ('hold', 'mouse'),
 ('repair', 'mouse'),
 ('no interaction', 'mouse'),
 ('buy', 'orange'),
 ('cut', 'orange'),
 ('eat', 'orange'),
 ('hold', 'orange'),
 ('inspect', 'orange'),
 ('peel', 'orange'),
 ('pick', 'orange'),
 ('squeeze', 'orange'),
 ('wash', 'orange'),
 ('no interaction', 'orange'),
 ('clean', 'oven'),
 ('hold', 'oven'),
 ('inspect', 'oven'),
 ('open', 'oven'),
 ('repair', 'oven'),
 ('operate', 'oven'),
 ('no interaction', 'oven'),
 ('check', 'parking meter'),
 ('pay', 'parking meter'),
 ('repair', 'parking meter'),
 ('no interaction', 'parking meter'),
 ('buy', 'pizza'),
 ('carry', 'pizza'),
 ('cook', 'pizza'),
 ('cut', 'pizza'),
 ('eat', 'pizza'),
 ('hold', 'pizza'),
 ('make', 'pizza'),
 ('pick up', 'pizza'),
 ('slide', 'pizza'),
 ('smell', 'pizza'),
 ('no interaction', 'pizza'),
 ('clean', 'refrigerator'),
 ('hold', 'refrigerator'),
 ('move', 'refrigerator'),
 ('open', 'refrigerator'),
 ('no interaction', 'refrigerator'),
 ('hold', 'remote'),
 ('point', 'remote'),
 ('swing', 'remote'),
 ('no interaction', 'remote'),
 ('carry', 'sandwich'),
 ('cook', 'sandwich'),
 ('cut', 'sandwich'),
 ('eat', 'sandwich'),
 ('hold', 'sandwich'),
 ('make', 'sandwich'),
 ('no interaction', 'sandwich'),
 ('cut with', 'scissors'),
 ('hold', 'scissors'),
 ('open', 'scissors'),
 ('no interaction', 'scissors'),
 ('clean', 'sink'),
 ('repair', 'sink'),
 ('wash', 'sink'),
 ('no interaction', 'sink'),
 ('carry', 'skateboard'),
 ('flip', 'skateboard'),
 ('grind', 'skateboard'),
 ('hold', 'skateboard'),
 ('jump', 'skateboard'),
 ('pick up', 'skateboard'),
 ('ride', 'skateboard'),
 ('sit on', 'skateboard'),
 ('stand on', 'skateboard'),
 ('no interaction', 'skateboard'),
 ('adjust', 'skis'),
 ('carry', 'skis'),
 ('hold', 'skis'),
 ('inspect', 'skis'),
 ('jump', 'skis'),
 ('pick up', 'skis'),
 ('repair', 'skis'),
 ('ride', 'skis'),
 ('stand on', 'skis'),
 ('wear', 'skis'),
 ('no interaction', 'skis'),
 ('adjust', 'snowboard'),
 ('carry', 'snowboard'),
 ('grind', 'snowboard'),
 ('hold', 'snowboard'),
 ('jump', 'snowboard'),
 ('ride', 'snowboard'),
 ('stand on', 'snowboard'),
 ('wear', 'snowboard'),
 ('no interaction', 'snowboard'),
 ('hold', 'spoon'),
 ('lick', 'spoon'),
 ('wash', 'spoon'),
 ('sip', 'spoon'),
 ('no interaction', 'spoon'),
 ('block', 'sports ball'),
 ('carry', 'sports ball'),
 ('catch', 'sports ball'),
 ('dribble', 'sports ball'),
 ('hit', 'sports ball'),
 ('hold', 'sports ball'),
 ('inspect', 'sports ball'),
 ('kick', 'sports ball'),
 ('pick up', 'sports ball'),
 ('serve', 'sports ball'),
 ('sign', 'sports ball'),
 ('spin', 'sports ball'),
 ('throw', 'sports ball'),
 ('no interaction', 'sports ball'),
 ('hold', 'stop sign'),
 ('stand under', 'stop sign'),
 ('stop at', 'stop sign'),
 ('no interaction', 'stop sign'),
 ('carry', 'suitcase'),
 ('drag', 'suitcase'),
 ('hold', 'suitcase'),
 ('hug', 'suitcase'),
 ('load', 'suitcase'),
 ('open', 'suitcase'),
 ('pack', 'suitcase'),
 ('pick up', 'suitcase'),
 ('zip', 'suitcase'),
 ('no interaction', 'suitcase'),
 ('carry', 'surfboard'),
 ('drag', 'surfboard'),
 ('hold', 'surfboard'),
 ('inspect', 'surfboard'),
 ('jump', 'surfboard'),
 ('lie on', 'surfboard'),
 ('load', 'surfboard'),
 ('ride', 'surfboard'),
 ('stand on', 'surfboard'),
 ('sit on', 'surfboard'),
 ('wash', 'surfboard'),
 ('no interaction', 'surfboard'),
 ('carry', 'teddy bear'),
 ('hold', 'teddy bear'),
 ('hug', 'teddy bear'),
 ('kiss', 'teddy bear'),
 ('no interaction', 'teddy bear'),
 ('carry', 'tennis racket'),
 ('hold', 'tennis racket'),
 ('inspect', 'tennis racket'),
 ('swing', 'tennis racket'),
 ('no interaction', 'tennis racket'),
 ('adjust', 'tie'),
 ('cut', 'tie'),
 ('hold', 'tie'),
 ('inspect', 'tie'),
 ('pull', 'tie'),
 ('tie', 'tie'),
 ('wear', 'tie'),
 ('no interaction', 'tie'),
 ('hold', 'toaster'),
 ('operate', 'toaster'),
 ('repair', 'toaster'),
 ('no interaction', 'toaster'),
 ('clean', 'toilet'),
 ('flush', 'toilet'),
 ('open', 'toilet'),
 ('repair', 'toilet'),
 ('sit on', 'toilet'),
 ('stand on', 'toilet'),
 ('wash', 'toilet'),
 ('no interaction', 'toilet'),
 ('brush with', 'toothbrush'),
 ('hold', 'toothbrush'),
 ('wash', 'toothbrush'),
 ('no interaction', 'toothbrush'),
 ('install', 'traffic light'),
 ('repair', 'traffic light'),
 ('stand under', 'traffic light'),
 ('stop at', 'traffic light'),
 ('no interaction', 'traffic light'),
 ('direct', 'truck'),
 ('drive', 'truck'),
 ('inspect', 'truck'),
 ('load', 'truck'),
 ('repair', 'truck'),
 ('ride', 'truck'),
 ('sit on', 'truck'),
 ('wash', 'truck'),
 ('no interaction', 'truck'),
 ('carry', 'umbrella'),
 ('hold', 'umbrella'),
 ('lose', 'umbrella'),
 ('open', 'umbrella'),
 ('repair', 'umbrella'),
 ('set', 'umbrella'),
 ('stand under', 'umbrella'),
 ('no interaction', 'umbrella'),
 ('hold', 'vase'),
 ('make', 'vase'),
 ('paint', 'vase'),
 ('no interaction', 'vase'),
 ('fill', 'wine glass'),
 ('hold', 'wine glass'),
 ('sip', 'wine glass'),
 ('toast', 'wine glass'),
 ('lick', 'wine glass'),
 ('wash', 'wine glass'),
 ('no interaction', 'wine glass'),
 ('feed', 'zebra'),
 ('hold', 'zebra'),
 ('pet', 'zebra'),
 ('watch', 'zebra'),
 ('no interaction', 'zebra')]

hico_verbs = ['adjust', 'assemble', 'block', 'blow', 'board', 'break', 'brush with', 'buy', 'carry', 'catch',
 'chase', 'check', 'clean', 'control', 'cook', 'cut', 'cut with', 'direct', 'drag', 'dribble',
 'drink with', 'drive', 'dry', 'eat', 'eat at', 'exit', 'feed', 'fill', 'flip', 'flush',
 'fly', 'greet', 'grind', 'groom', 'herd', 'hit', 'hold', 'hop on', 'hose', 'hug',
 'hunt', 'inspect', 'install', 'jump', 'kick', 'kiss', 'lasso', 'launch', 'lick', 'lie on', 
 'lift', 'light', 'load', 'lose', 'make', 'milk', 'move', 'no interaction', 'open', 'operate',
 'pack', 'paint', 'park', 'pay', 'peel', 'pet', 'pick', 'pick up', 'point', 'pour', 
 'pull', 'push', 'race', 'read', 'release', 'repair', 'ride', 'row', 'run', 'sail', 
 'scratch', 'serve', 'set', 'shear', 'sign', 'sip', 'sit at', 'sit on', 'slide', 'smell', 
 'spin', 'squeeze', 'stab', 'stand on', 'stand under', 'stick', 'stir', 'stop at', 'straddle', 'swing', 
 'tag', 'talk on', 'teach', 'text on', 'throw', 'tie', 'toast', 'train', 'turn', 'type on', 
 'walk', 'wash', 'watch', 'wave', 'wear', 'wield', 'zip']
 
hico_objects = ['person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus', 'train', 'truck', 'boat', 'traffic_light', 
'fire_hydrant', 'stop_sign', 'parking_meter', 'bench', 'bird', 'cat', 'dog', 'horse', 'sheep', 'cow', 'elephant', 'bear', 
'zebra', 'giraffe', 'backpack', 'umbrella', 'handbag', 'tie', 'suitcase', 'frisbee', 'skis', 'snowboard', 'sports_ball', 
'kite', 'baseball_bat', 'baseball_glove', 'skateboard', 'surfboard', 'tennis_racket', 'bottle', 'wine_glass', 'cup', 'fork',
'knife', 'spoon', 'bowl', 'banana', 'apple', 'sandwich', 'orange', 'broccoli', 'carrot', 'hot_dog', 'pizza', 'donut', 'cake', 
'chair', 'couch', 'potted_plant', 'bed', 'dining_table', 'toilet', 'tv', 'laptop', 'mouse', 'remote', 'keyboard', 'cell_phone',
'microwave', 'oven', 'toaster', 'sink', 'refrigerator', 'book', 'clock', 'vase', 'scissors', 'teddy_bear', 'hair_drier', 'toothbrush']

hico_verbs_sentence = ['a photo of a person is adjusting the object',
 'a photo of a person is assembling the object',
 'a photo of a person is blocking the object',
 'a photo of a person is blowing the object',
 'a photo of a person is boarding the object',
 'a photo of a person is breaking the object',
 'a photo of a person is brushing with the object',
 'a photo of a person is buying the object',
 'a photo of a person is carrying the object',
 'a photo of a person is catching the object',
 'a photo of a person is chasing the object',
 'a photo of a person is checking the object',
 'a photo of a person is cleaning the object',
 'a photo of a person is controling the object',
 'a photo of a person is cooking the object',
 'a photo of a person is cutting the object',
 'a photo of a person is cutting with the object',
 'a photo of a person is directing the object',
 'a photo of a person is draging the object',
 'a photo of a person is dribbling the object',
 'a photo of a person is drinking with the object',
 'a photo of a person is driving the object',
 'a photo of a person is drying the object',
 'a photo of a person is eating the object',
 'a photo of a person is eating at the object',
 'a photo of a person is exiting the object',
 'a photo of a person is feeding the object',
 'a photo of a person is filling the object',
 'a photo of a person is flipping the object',
 'a photo of a person is flushing the object',
 'a photo of a person is flying the object',
 'a photo of a person is greeting the object',
 'a photo of a person is grinding the object',
 'a photo of a person is grooming the object',
 'a photo of a person is herding the object',
 'a photo of a person is hiting the object',
 'a photo of a person is holding the object',
 'a photo of a person is hopping on the object',
 'a photo of a person is hosing the object',
 'a photo of a person is hugging the object',
 'a photo of a person is hunting the object',
 'a photo of a person is inspecting the object',
 'a photo of a person is installing the object',
 'a photo of a person is jumping the object',
 'a photo of a person is kicking the object',
 'a photo of a person is kissing the object',
 'a photo of a person is lassoing the object',
 'a photo of a person is launching the object',
 'a photo of a person is licking the object',
 'a photo of a person is lying on the object',
 'a photo of a person is lifting the object',
 'a photo of a person is lighting the object',
 'a photo of a person is loading the object',
 'a photo of a person is losing the object',
 'a photo of a person is making the object',
 'a photo of a person is milking the object',
 'a photo of a person is moving the object',
 'a photo of a person is not interacting with the object',
 'a photo of a person is opening the object',
 'a photo of a person is operating the object',
 'a photo of a person is packing the object',
 'a photo of a person is painting the object',
 'a photo of a person is parking the object',
 'a photo of a person is paying the object',
 'a photo of a person is peeling the object',
 'a photo of a person is petting the object',
 'a photo of a person is picking the object',
 'a photo of a person is picking up the object',
 'a photo of a person is pointing the object',
 'a photo of a person is pouring the object',
 'a photo of a person is pulling the object',
 'a photo of a person is pushing the object',
 'a photo of a person is racing the object',
 'a photo of a person is reading the object',
 'a photo of a person is releasing the object',
 'a photo of a person is repairing the object',
 'a photo of a person is riding the object',
 'a photo of a person is rowing the object',
 'a photo of a person is running the object',
 'a photo of a person is sailing the object',
 'a photo of a person is scratching the object',
 'a photo of a person is serving the object',
 'a photo of a person is setting the object',
 'a photo of a person is shearing the object',
 'a photo of a person is signing the object',
 'a photo of a person is siping the object',
 'a photo of a person is sitting at the object',
 'a photo of a person is sitting on the object',
 'a photo of a person is sliding the object',
 'a photo of a person is smelling the object',
 'a photo of a person is spining the object',
 'a photo of a person is squeezing the object',
 'a photo of a person is stabbing the object',
 'a photo of a person is standing on the object',
 'a photo of a person is standing under the object',
 'a photo of a person is sticking the object',
 'a photo of a person is stirring the object',
 'a photo of a person is stopping at the object',
 'a photo of a person is straddling the object',
 'a photo of a person is swinging the object',
 'a photo of a person is tagging the object',
 'a photo of a person is talking on the object',
 'a photo of a person is teaching the object',
 'a photo of a person is texting on the object',
 'a photo of a person is throwing the object',
 'a photo of a person is tying the object',
 'a photo of a person is toasting the object',
 'a photo of a person is training the object',
 'a photo of a person is turning the object',
 'a photo of a person is typing on the object',
 'a photo of a person is walking the object',
 'a photo of a person is washing the object',
 'a photo of a person is watching the object',
 'a photo of a person is waving the object',
 'a photo of a person is wearing the object',
 'a photo of a person is wielding the object',
 'a photo of a person is zipping the object']

hico_object_sentence = ['a photo of a person is interacting with a person',
 'a photo of a person is interacting with a bicycle',
 'a photo of a person is interacting with a car',
 'a photo of a person is interacting with a motorcycle',
 'a photo of a person is interacting with an airplane',
 'a photo of a person is interacting with a bus',
 'a photo of a person is interacting with a train',
 'a photo of a person is interacting with a truck',
 'a photo of a person is interacting with a boat',
 'a photo of a person is interacting with a traffic_light',
 'a photo of a person is interacting with a fire_hydrant',
 'a photo of a person is interacting with a stop_sign',
 'a photo of a person is interacting with a parking_meter',
 'a photo of a person is interacting with a bench',
 'a photo of a person is interacting with a bird',
 'a photo of a person is interacting with a cat',
 'a photo of a person is interacting with a dog',
 'a photo of a person is interacting with a horse',
 'a photo of a person is interacting with a sheep',
 'a photo of a person is interacting with a cow',
 'a photo of a person is interacting with a elephant',
 'a photo of a person is interacting with a bear',
 'a photo of a person is interacting with a zebra',
 'a photo of a person is interacting with a giraffe',
 'a photo of a person is interacting with a backpack',
 'a photo of a person is interacting with an umbrella',
 'a photo of a person is interacting with a handbag',
 'a photo of a person is interacting with a tie',
 'a photo of a person is interacting with a suitcase',
 'a photo of a person is interacting with a frisbee',
 'a photo of a person is interacting with a skis',
 'a photo of a person is interacting with a snowboard',
 'a photo of a person is interacting with a sports_ball',
 'a photo of a person is interacting with a kite',
 'a photo of a person is interacting with a baseball_bat',
 'a photo of a person is interacting with a baseball_glove',
 'a photo of a person is interacting with a skateboard',
 'a photo of a person is interacting with a surfboard',
 'a photo of a person is interacting with a tennis_racket',
 'a photo of a person is interacting with a bottle',
 'a photo of a person is interacting with a wine_glass',
 'a photo of a person is interacting with a cup',
 'a photo of a person is interacting with a fork',
 'a photo of a person is interacting with a knife',
 'a photo of a person is interacting with a spoon',
 'a photo of a person is interacting with a bowl',
 'a photo of a person is interacting with a banana',
 'a photo of a person is interacting with an apple',
 'a photo of a person is interacting with a sandwich',
 'a photo of a person is interacting with an orange',
 'a photo of a person is interacting with a broccoli',
 'a photo of a person is interacting with a carrot',
 'a photo of a person is interacting with a hot_dog',
 'a photo of a person is interacting with a pizza',
 'a photo of a person is interacting with a donut',
 'a photo of a person is interacting with a cake',
 'a photo of a person is interacting with a chair',
 'a photo of a person is interacting with a couch',
 'a photo of a person is interacting with a potted_plant',
 'a photo of a person is interacting with a bed',
 'a photo of a person is interacting with a dining_table',
 'a photo of a person is interacting with a toilet',
 'a photo of a person is interacting with a tv',
 'a photo of a person is interacting with a laptop',
 'a photo of a person is interacting with a mouse',
 'a photo of a person is interacting with a remote',
 'a photo of a person is interacting with a keyboard',
 'a photo of a person is interacting with a cell_phone',
 'a photo of a person is interacting with a microwave',
 'a photo of a person is interacting with an oven',
 'a photo of a person is interacting with a toaster',
 'a photo of a person is interacting with a sink',
 'a photo of a person is interacting with a refrigerator',
 'a photo of a person is interacting with a book',
 'a photo of a person is interacting with a clock',
 'a photo of a person is interacting with a vase',
 'a photo of a person is interacting with a scissors',
 'a photo of a person is interacting with a teddy_bear',
 'a photo of a person is interacting with a hair_drier',
 'a photo of a person is interacting with a toothbrush']


hico_verbs_sentence_reb_1 = ['person adjust the object',
 'person assemble the object',
 'person block the object',
 'person blow the object',
 'person board the object',
 'person break the object',
 'person brush with the object',
 'person buy the object',
 'person carry the object',
 'person catch the object',
 'person chase the object',
 'person check the object',
 'person clean the object',
 'person control the object',
 'person cook the object',
 'person cut the object',
 'person cut with the object',
 'person direct the object',
 'person drag the object',
 'person dribble the object',
 'person drink with the object',
 'person drive the object',
 'person dry the object',
 'person eat the object',
 'person eat at the object',
 'person exit the object',
 'person feed the object',
 'person fill the object',
 'person flip the object',
 'person flush the object',
 'person fly the object',
 'person greet the object',
 'person grind the object',
 'person groom the object',
 'person herd the object',
 'person hit the object',
 'person hold the object',
 'person hop on the object',
 'person hose the object',
 'person hug the object',
 'person hunt the object',
 'person inspect the object',
 'person install the object',
 'person jump the object',
 'person kick the object',
 'person kiss the object',
 'person lasso the object',
 'person launch the object',
 'person lick the object',
 'person lie on the object',
 'person lift the object',
 'person light the object',
 'person load the object',
 'person lose the object',
 'person make the object',
 'person milk the object',
 'person move the object',
 'person not interact with the object',
 'person open the object',
 'person operate the object',
 'person pack the object',
 'person paint the object',
 'person park the object',
 'person pay the object',
 'person peel the object',
 'person pet the object',
 'person pick the object',
 'person pick up the object',
 'person point the object',
 'person pour the object',
 'person pull the object',
 'person push the object',
 'person race the object',
 'person read the object',
 'person release the object',
 'person repair the object',
 'person ride the object',
 'person row the object',
 'person run the object',
 'person sail the object',
 'person scratch the object',
 'person serve the object',
 'person set the object',
 'person shear the object',
 'person sign the object',
 'person sip the object',
 'person sit at the object',
 'person sit on the object',
 'person slide the object',
 'person smell the object',
 'person spin the object',
 'person squeeze the object',
 'person stab the object',
 'person stand on the object',
 'person stand under the object',
 'person stick the object',
 'person stir the object',
 'person stop at the object',
 'person straddle the object',
 'person swing the object',
 'person tag the object',
 'person talk on the object',
 'person teach the object',
 'person text on the object',
 'person throw the object',
 'person tie the object',
 'person toast the object',
 'person train the object',
 'person turn the object',
 'person type on the object',
 'person walk the object',
 'person wash the object',
 'person watch the object',
 'person wave the object',
 'person wear the object',
 'person wield the object',
 'person zip the object']

hico_verbs_sentence_reb_2 = ['a example of the person is adjusting the object',
 'a example of the person is assembling the object',
 'a example of the person is blocking the object',
 'a example of the person is blowing the object',
 'a example of the person is boarding the object',
 'a example of the person is breaking the object',
 'a example of the person is brushing with the object',
 'a example of the person is buying the object',
 'a example of the person is carrying the object',
 'a example of the person is catching the object',
 'a example of the person is chasing the object',
 'a example of the person is checking the object',
 'a example of the person is cleaning the object',
 'a example of the person is controling the object',
 'a example of the person is cooking the object',
 'a example of the person is cutting the object',
 'a example of the person is cutting with the object',
 'a example of the person is directing the object',
 'a example of the person is draging the object',
 'a example of the person is dribbling the object',
 'a example of the person is drinking with the object',
 'a example of the person is driving the object',
 'a example of the person is drying the object',
 'a example of the person is eating the object',
 'a example of the person is eating at the object',
 'a example of the person is exiting the object',
 'a example of the person is feeding the object',
 'a example of the person is filling the object',
 'a example of the person is flipping the object',
 'a example of the person is flushing the object',
 'a example of the person is flying the object',
 'a example of the person is greeting the object',
 'a example of the person is grinding the object',
 'a example of the person is grooming the object',
 'a example of the person is herding the object',
 'a example of the person is hiting the object',
 'a example of the person is holding the object',
 'a example of the person is hopping on the object',
 'a example of the person is hosing the object',
 'a example of the person is hugging the object',
 'a example of the person is hunting the object',
 'a example of the person is inspecting the object',
 'a example of the person is installing the object',
 'a example of the person is jumping the object',
 'a example of the person is kicking the object',
 'a example of the person is kissing the object',
 'a example of the person is lassoing the object',
 'a example of the person is launching the object',
 'a example of the person is licking the object',
 'a example of the person is lying on the object',
 'a example of the person is lifting the object',
 'a example of the person is lighting the object',
 'a example of the person is loading the object',
 'a example of the person is losing the object',
 'a example of the person is making the object',
 'a example of the person is milking the object',
 'a example of the person is moving the object',
 'a example of the person is not interacting with the object',
 'a example of the person is opening the object',
 'a example of the person is operating the object',
 'a example of the person is packing the object',
 'a example of the person is painting the object',
 'a example of the person is parking the object',
 'a example of the person is paying the object',
 'a example of the person is peeling the object',
 'a example of the person is petting the object',
 'a example of the person is picking the object',
 'a example of the person is picking up the object',
 'a example of the person is pointing the object',
 'a example of the person is pouring the object',
 'a example of the person is pulling the object',
 'a example of the person is pushing the object',
 'a example of the person is racing the object',
 'a example of the person is reading the object',
 'a example of the person is releasing the object',
 'a example of the person is repairing the object',
 'a example of the person is riding the object',
 'a example of the person is rowing the object',
 'a example of the person is running the object',
 'a example of the person is sailing the object',
 'a example of the person is scratching the object',
 'a example of the person is serving the object',
 'a example of the person is setting the object',
 'a example of the person is shearing the object',
 'a example of the person is signing the object',
 'a example of the person is siping the object',
 'a example of the person is sitting at the object',
 'a example of the person is sitting on the object',
 'a example of the person is sliding the object',
 'a example of the person is smelling the object',
 'a example of the person is spining the object',
 'a example of the person is squeezing the object',
 'a example of the person is stabbing the object',
 'a example of the person is standing on the object',
 'a example of the person is standing under the object',
 'a example of the person is sticking the object',
 'a example of the person is stirring the object',
 'a example of the person is stopping at the object',
 'a example of the person is straddling the object',
 'a example of the person is swinging the object',
 'a example of the person is tagging the object',
 'a example of the person is talking on the object',
 'a example of the person is teaching the object',
 'a example of the person is texting on the object',
 'a example of the person is throwing the object',
 'a example of the person is tying the object',
 'a example of the person is toasting the object',
 'a example of the person is training the object',
 'a example of the person is turning the object',
 'a example of the person is typing on the object',
 'a example of the person is walking the object',
 'a example of the person is washing the object',
 'a example of the person is watching the object',
 'a example of the person is waving the object',
 'a example of the person is wearing the object',
 'a example of the person is wielding the object',
 'a example of the person is zipping the object']