vcoco_obj_text_label = [(0, 'a photo of a person and a person'), (1, 'a photo of a person and a bicycle'),
                        (2, 'a photo of a person and a car'), (3, 'a photo of a person and a motorcycle'),
                        (4, 'a photo of a person and an airplane'), (5, 'a photo of a person and a bus'),
                        (6, 'a photo of a person and a train'), (7, 'a photo of a person and a truck'),
                        (8, 'a photo of a person and a boat'), (9, 'a photo of a person and a traffic light'),
                        (10, 'a photo of a person and a fire hydrant'), (11, 'a photo of a person and a stop sign'),
                        (12, 'a photo of a person and a parking meter'), (13, 'a photo of a person and a bench'),
                        (14, 'a photo of a person and a bird'), (15, 'a photo of a person and a cat'),
                        (16, 'a photo of a person and a dog'), (17, 'a photo of a person and a horse'),
                        (18, 'a photo of a person and a sheep'), (19, 'a photo of a person and a cow'),
                        (20, 'a photo of a person and an elephant'), (21, 'a photo of a person and a bear'),
                        (22, 'a photo of a person and a zebra'), (23, 'a photo of a person and a giraffe'),
                        (24, 'a photo of a person and a backpack'), (25, 'a photo of a person and a umbrella'),
                        (26, 'a photo of a person and a handbag'), (27, 'a photo of a person and a tie'),
                        (28, 'a photo of a person and a suitcase'), (29, 'a photo of a person and a frisbee'),
                        (30, 'a photo of a person and a skis'), (31, 'a photo of a person and a snowboard'),
                        (32, 'a photo of a person and a sports ball'), (33, 'a photo of a person and a kite'),
                        (34, 'a photo of a person and a baseball bat'),
                        (35, 'a photo of a person and a baseball glove'),
                        (36, 'a photo of a person and a skateboard'), (37, 'a photo of a person and a surfboard'),
                        (38, 'a photo of a person and a tennis racket'), (39, 'a photo of a person and a bottle'),
                        (40, 'a photo of a person and a wine glass'), (41, 'a photo of a person and a cup'),
                        (42, 'a photo of a person and a fork'), (43, 'a photo of a person and a knife'),
                        (44, 'a photo of a person and a spoon'), (45, 'a photo of a person and a bowl'),
                        (46, 'a photo of a person and a banana'), (47, 'a photo of a person and an apple'),
                        (48, 'a photo of a person and a sandwich'), (49, 'a photo of a person and an orange'),
                        (50, 'a photo of a person and a broccoli'), (51, 'a photo of a person and a carrot'),
                        (52, 'a photo of a person and a hot dog'), (53, 'a photo of a person and a pizza'),
                        (54, 'a photo of a person and a donut'), (55, 'a photo of a person and a cake'),
                        (56, 'a photo of a person and a chair'), (57, 'a photo of a person and a couch'),
                        (58, 'a photo of a person and a potted plant'), (59, 'a photo of a person and a bed'),
                        (60, 'a photo of a person and a dining table'), (61, 'a photo of a person and a toilet'),
                        (62, 'a photo of a person and a tv'), (63, 'a photo of a person and a laptop'),
                        (64, 'a photo of a person and a mouse'), (65, 'a photo of a person and a remote'),
                        (66, 'a photo of a person and a keyboard'), (67, 'a photo of a person and a cell phone'),
                        (68, 'a photo of a person and a microwave'), (69, 'a photo of a person and an oven'),
                        (70, 'a photo of a person and a toaster'), (71, 'a photo of a person and a sink'),
                        (72, 'a photo of a person and a refrigerator'), (73, 'a photo of a person and a book'),
                        (74, 'a photo of a person and a clock'), (75, 'a photo of a person and a vase'),
                        (76, 'a photo of a person and a scissors'), (77, 'a photo of a person and a teddy bear'),
                        (78, 'a photo of a person and a hair drier'), (79, 'a photo of a person and a toothbrush'),
                        ]

vcoco_hoi_text_label = {(0, 1): 'a photo of a person holding a person', 
                        (3, 1): 'a photo of a person looking at a person', 
                        (11, 1): 'a photo of a person carrying a person', 
                        (15, 1): 'a photo of a person cutting a person', 
                        (0, 2): 'a photo of a person holding a bicycle',
                        (1, 2): 'a photo of a person sitting on a bicycle', 
                        (2, 2): 'a photo of a person riding a bicycle', 
                        (3, 2): 'a photo of a person looking at a bicycle', 
                        (11, 2): 'a photo of a person carrying a bicycle', 
                        (2, 3): 'a photo of a person riding a car', 
                        (3, 3): 'a photo of a person looking at a car', 
                        (11, 3): 'a photo of a person carrying a car', 
                        (0, 4): 'a photo of a person holding a motorcycle', 
                        (1, 4): 'a photo of a person sitting on a motorcycle', 
                        (2, 4): 'a photo of a person riding a motorcycle', 
                        (3, 4): 'a photo of a person looking at a motorcycle', 
                        (3, 5): 'a photo of a person looking at a airplane', 
                        (2, 6): 'a photo of a person riding a bus', 
                        (3, 6): 'a photo of a person looking at a bus', 
                        (2, 7): 'a photo of a person riding a train', 
                        (3, 7): 'a photo of aperson looking at a train', 
                        (0, 8): 'a photo of a person holding a truck', 
                        (2, 8): 'a photo of a person riding a truck', (3, 8): 'a photo of a person looking at a truck', 
                        (0, 9): 'a photo of a person holding a boat', (2, 9): 'a photo of a person riding a boat', 
                        (3, 9): 'a photo of a person looking at a boat', 
                        (3, 10): 'a photo of a person looking at a traffic light', 
                        (3, 11): 'a photo of a person looking at a fire hydrant', 
                        (0, 14): 'a photo of a person holding a bench', (1, 14): 'a photo of a person sitting on a bench', 
                        (3, 14): 'a photo of a person looking at a bench', (9, 14): 'a photo of a person laying on a bench', 
                        (0, 15): 'aphoto of a person holding a bird', (3, 15): 'a photo of a person looking at a bird', 
                        (0, 16): 'a photo of a person holding a cat', (3, 16): 'a photo of a person looking at a cat', 
                        (0, 17): 'a photo of a person holding a dog', (3, 17): 'a photo of a personlooking at a dog', 
                        (11, 17): 'a photo of a person carrying a dog',
                        (0, 18): 'a photo of a person holding a horse', (1, 18): 'a photo of a person sitting on a horse', 
                        (2, 18): 'a photo of a person riding a horse', (3, 18): 'a photo of a person looking at a horse', 
                        (0, 19): 'a photo of a person holding a sheep', (3, 19): 'a photo of a person looking at a sheep', 
                        (11, 19): 'a photo of a person carrying a sheep', (15, 19): 'a photo of a person cutting a sheep', 
                        (0, 20): 'a photo of a person holding a cow', (3,20): 'a photo of a person looking at a cow', 
                        (0, 21): 'a photo of a person holding a elephant', (1, 21): 'a photo of a person sitting on a elephant', 
                        (2, 21): 'a photo of a person riding a elephant', (3, 21): 'a photo of a person looking at a elephant', 
                        (3, 24): 'a photo of a person looking at a giraffe', 
                        (0, 25): 'a photo of a person holding a backpack', (1, 25): 'a photo of a person sitting on a backpack', 
                        (3, 25): 'a photo of a person looking at a backpack', 
                        (11, 25): 'a photo of a person carrying a backpack', 
                        (0, 26): 'a photo of a person holding a umbrella', (3, 26): 'a photo of a person looking at a umbrella', 
                        (11, 26): 'a photo of a person carrying a umbrella', 
                        (0, 27): 'a photo of a person holding a handbag', (1, 27): 'a photo of a person sitting ona handbag', 
                        (3, 27): 'a photo of a person looking at a handbag', (11, 27): 'a photo of a person carrying a handbag', 
                        (0, 28): 'a photo of a person holding a tie', (3, 28): 'a photo of a person looking at a tie', 
                        (15, 28): 'a photo of a person cutting a tie', (0, 29): 'a photo of a person holding a suitcase', 
                        (1, 29): 'a photo of a person sitting on a suitcase', (3, 29): 'a photo of a person looking at a suitcase', 
                        (11, 29): 'a photo of a person carrying a suitcase', 
                        (0, 30): 'a photo of a person holding a frisbee', 
                        (3, 30): 'a photo of a person looking at a frisbee', 
                        (11, 30): 'a photo of a person carrying a frisbee', 
                        (12, 30): 'a photo of a person throwing a frisbee', 
                        (13, 30): 'a photo of a person catching a frisbee', 
                        (0, 31): 'a photo of a person holdinga skis', (3, 31): 'a photo of a person looking at a skis', 
                        (8, 31): 'a photo of a person jumping on a skis', (11, 31): 'a photoof a person carrying a skis', 
                        (17, 31): 'a photo of a person skiing on a skis', 
                        (0, 32): 'a photo of a person holding a snowboard', 
                        (3, 32): 'a photo of a person looking at a snowboard', 
                        (8, 32): 'a photo of a person jumping on a snowboard', (11, 32): 'a photo of a person carrying a snowboard', 
                        (23, 32): 'a photo of a person snowboarding a snowboard', 
                        (0, 33): 'a photo of a personholding a sports ball', (3, 33): 'a photo of a person looking at a sports ball', 
                        (5, 33): 'a photo of a person hitting a sportsball', 
                        (11, 33): 'a photo of a person carrying a sports ball', 
                        (12, 33): 'a photo of a person throwing a sports ball', 
                        (13, 33): 'a photo of a person catching a sports ball', 
                        (21, 33): 'a photo of a person kicking a sports ball', (0, 34): 'a photo of a person holding a kite', 
                        (3, 34): 'a photo of a person looking at a kite', (11, 34): 'a photo of a person carrying a kite', 
                        (0, 35): 'a photo of a person holding a baseball bat', 
                        (3, 35): 'a photo of a person looking at a baseball bat', 
                        (4, 35): 'a photo of aperson hitting with a baseball bat', (11, 35): 'a photo of a person carrying a baseball bat', 
                        (0, 36): 'a photo of a person holding a baseball glove', (3, 36): 'a photo of a person looking at a baseball glove', 
                        (0, 37): 'a photo of a person holding a skateboard', (3, 37): 'a photo of a person looking at a skateboard', 
                        (8, 37): 'a photo of a person jumping on a skateboard', (11, 37): 'a photo of a person carrying a skateboard', 
                        (15, 37): 'a photo of a person cutting a skateboard', (19, 37): 'a photo of a person skateboarding a skateboard', 
                        (0, 38): 'a photo of a person holding a surfboard', (3, 38): 'a photo of a person looking at asurfboard', 
                        (8, 38): 'a photo of a person jumping on a surfboard', (11, 38): 'a photo of a person carrying a surfboard', 
                        (18, 38): 'a photo of a person surfing a surfboard', (0, 39): 'a photo of a person holding a tennis racket', 
                        (3, 39): 'a photo of a person looking at a tennis racket', (4, 39): 'a photo of a person hitting with a tennis racket', 
                        (11, 39): 'a photo of a person carrying a tennis racket', (0, 40): 'a photo of a person holding a bottle', 
                        (3, 40): 'a photo of a person looking at a bottle', (11, 40): 'a photo of a person carrying a bottle', 
                        (20, 40): 'a photo of a person drinking with a bottle', (0, 41): 'a photo of a person holding a wine glass', 
                        (3, 41): 'a photo of a person looking at a wine glass', 
                        (11, 41): 'a photo of a person carrying a wine glass', 
                        (20, 41): 'a photo of a person drinking with a wine glass', 
                        (0, 42): 'a photo of a person holding a cup', (3, 42): 'a photo of a person looking at a cup', 
                        (11, 42): 'a photo of a person carrying a cup', (20, 42): 'a photo of a person drinking with a cup', 
                        (0, 43): 'a photo of a person holding a fork', (3, 43): 'a photo of a person looking at a fork', 
                        (7, 43): 'a photo of a person eating with a fork', (14, 43): 'a photo of a person cutting with a fork', 
                        (0, 44): 'a photo of a person holding a knife', (3, 44): 'a photo of a person looking at a knife', 
                        (7, 44): 'a photo of a person eating with a knife', (14, 44): 'a photo of a person cutting with a knife', 
                        (0, 45): 'a photo of a person holding a spoon', (3, 45): 'a photo of a person looking at a spoon', 
                        (7, 45): 'a photo of a person eating with a spoon', 
                        (0, 46): 'a photo of a person holding a bowl', (3, 46): 'a photo of a person looking at a bowl', 
                        (15, 46): 'a photo of a person cutting a bowl', (20, 46): 'a photo of a person drinking with a bowl',
                        (0, 47): 'a photo of a person holding a banana', (3, 47): 'a photo of a person looking at a banana', 
                        (6, 47): 'a photo of a person eating a banana', (11, 47): 'a photo of a person carrying a banana', 
                        (15, 47): 'a photo of a person cutting a banana', 
                        (0, 48): 'a photo of a person holding a apple', (3, 48): 'a photo of a person looking at a apple', 
                        (6, 48): 'a photo of a person eating a apple', (15, 48): 'a photo of a person cutting a apple', 
                        (0, 49): 'a photo of a person holding a sandwich', (3, 49): 'a photo of a person looking at a sandwich', 
                        (6, 49): 'a photo of a person eating a sandwich', (15, 49): 'a photo of a person cutting a sandwich', 
                        (0, 50): 'a photo of a person holding a orange', (6, 50): 'a photo of a person eating a orange', 
                        (11, 50): 'a photoof a person carrying a orange', (15, 50): 'a photo of a person cutting a orange', 
                        (0, 51): 'a photo of a person holding a broccoli', (3, 51): 'a photo of a person looking at a broccoli', 
                        (6, 51): 'a photo of a person eating a broccoli', (15, 51): 'a photoof a person cutting a broccoli', 
                        (0, 52): 'a photo of a person holding a carrot', (6, 52): 'a photo of a person eating a carrot', 
                        (15, 52): 'a photo of a person cutting a carrot', 
                        (0, 53): 'a photo of a person holding a hot dog', (3, 53): 'a photo of a person looking at a hot dog', 
                        (6, 53): 'a photo of a person eating a hot dog', (15, 53): 'a photo of a person cutting a hot dog',
                        (0, 54): 'a photo of a person holding a pizza', (3, 54): 'a photo of a person looking at a pizza', 
                        (6, 54): 'a photo of a personeating a pizza', (15, 54): 'a photo of a person cutting a pizza', 
                        (0, 55): 'a photo of a person holding a donut', (3, 55): 'a photo of a person looking at a donut', 
                        (6, 55): 'a photo of a person eating a donut', (11, 55): 'a photo of a person carrying a donut', 
                        (15, 55): 'a photo of a person cutting a donut', (0, 56): 'a photo of a person holding a cake', 
                        (3, 56): 'a photo of a person looking at a cake', (6, 56): 'a photo of a person eating a cake', 
                        (15, 56): 'a photo of a person cutting a cake', 
                        (0, 57): 'a photo of a person holding a chair', (1, 57): 'a photo of a person sitting on a chair', 
                        (3, 57): 'a photo of a person looking at a chair', (9, 57): 'a photo of a person laying on a chair', 
                        (1, 58): 'a photo of a person sitting on a couch', (9, 58): 'a photo of a person laying on a couch', 
                        (3, 59): 'a photo of a person looking at a potted plant', (0, 60): 'a photo of a person holding a bed', 
                        (1, 60): 'a photo of a person sitting on a bed', (9, 60): 'a photo of a person laying on a bed', 
                        (0, 61): 'a photo of a person holding a dining table', (1, 61): 'a photo of a person sitting on a dining table', 
                        (3, 61): 'a photo of a person looking at a dining table', (9, 61): 'a photo of a person laying on a dining table', 
                        (1, 62): 'a photo of a person sitting on a toilet', (3, 62): 'a photo of a person looking at a toilet', 
                        (9, 62): 'a photo of a person laying on a toilet', (3, 63): 'a photo ofa person looking at a tv', 
                        (0, 64): 'a photo of a person holding a laptop', (3, 64): 'a photo of a person looking at a laptop',
                        (11, 64): 'a photo of a person carrying a laptop', (15, 64): 'a photo of a person cutting a laptop', 
                        (16, 64): 'a photo of a person working on a laptop', (0, 65): 'a photo of a person holding a mouse', 
                        (3, 65): 'a photo of a person looking at a mouse', (0, 66): 'a photo of a person holding a remote', 
                        (3, 66): 'a photo of a person looking at a remote', (0, 67): 'a photo of a personholding a keyboard', 
                        (3, 67): 'a photo of a person looking at a keyboard', (0, 68): 'a photo of a person holding a cell phone',
                        (3, 68): 'a photo of a person looking at a cell phone', (10, 68): 'a photo of a person talking on a cell phone', 
                        (11, 68): 'a photo of a person carrying a cell phone', (0, 73): 'a photo of a person holding a refrigerator', 
                        (3, 73): 'a photo of a person looking at a refrigerator', (0, 74): 'a photo of a person holding a book', 
                        (3, 74): 'a photo of a person looking at a book', (11, 74): 'a photo of a person carrying a book', 
                        (15, 74): 'a photo of a person cutting a book', (22, 74): 'a photo of a person reading a book', 
                        (3, 75): 'a photo of a person looking at a clock', (11, 75): 'a photo of a person carrying a clock', 
                        (0, 77): 'a photo of a person holding a scissors', (3, 77): 'a photo of a person looking at a scissors', 
                        (14, 77): 'a photo of a person cuttingwith a scissors', (0, 78): 'a photo of a person holding a teddy bear', 
                        (11, 78): 'a photo of a person carrying a teddy bear', (0, 79): 'a photo of a person holding a hair drier', 
                        (0, 80): 'a photo of a person holding a toothbrush'}